import Head from "next/head";
import { Inter } from "next/font/google";
import { Google } from "@/plugins/google";
import { Facebook } from "@/plugins/facebook";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto h-screen w-full flex items-center justify-center text-center flex-col gap-5">
        <Google
          clientId={
            "267711026176-4qvtdrssib8rid36b01kp3eoduh1ie9u.apps.googleusercontent.com"
          }
        ></Google>

        <Facebook appId={"300479674903257"}></Facebook>
      </div>
    </>
  );
}
